cachedir = "/cache"
logfile = "/config/hylde.log"
cachedbfile = "/config/cache.db"

[downloader.jdownloader]
email = "TO BE SET"
password = "TO BE SET"
devicename = "TO BE SET"
outputdir = "/output"                 # base directory that jdownloader uses for downloads
externaloutputdir = "/temp/downloads" # external path to jdl dl base dir
