port = 5000
maxtimeout = 55             # maximum time in seconds to wait until responding to http requests to avoid client timeouts
cachedir = "/cache"
cachedbfile = "/config/cache.db"
logfile = "/config/hylde.log"
loglevel = "INFO"

[downloader.jdownloader]
email = "TO BE SET"
password = "TO BE SET"
devicename = "TO BE SET"
outputdir = "/output"                 # base directory that jdownloader uses for downloads
externaloutputdir = "/temp/downloads" # external path to jdl dl base dir
