port = 5000
maxtimeout = 55             # maximum time in seconds to wait until responding to http requests to avoid client timeouts
cachedir = "/cache"
cachedbfile = "/config/cache.db"
logfile = "/config/hylde.log"
loglevel = "INFO"

[registry]
downloader_patterns = [
  ["://jpg\\d+\\.\\w{2,8}/i(?:mg|mage)?/.", "gallerydl"],
  ["://bunkr+\\.\\w{2,8}/(?:f|d|i|v)/.", "gallerydl"],
  [".*", "jdownloader"],
]

[downloader.jdownloader]
email = "TO BE SET"
password = "TO BE SET"
devicename = "TO BE SET"
outputdir = "/output"                 # base directory that jdownloader uses for downloads
externaloutputdir = "/temp/downloads" # external path to jdl dl base dir
